//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class EmployeeSkill
{
    public int Id { get; set; }
    public int EmployeeId { get; set; }
    public int SkillId { get; set; }
    public decimal ProfiencyLevel { get; set; }
    public Nullable<decimal> Experience { get; set; }
    public Nullable<decimal> LastUsed { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual Skill Skill { get; set; }
}
